//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSH.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsers
    {
        public AspNetUsers()
        {
            this.CompanyAsset = new HashSet<CompanyAsset>();
            this.CompanyAsset1 = new HashSet<CompanyAsset>();
            this.Member = new HashSet<Member>();
            this.Member1 = new HashSet<Member>();
            this.TicketReceive = new HashSet<TicketReceive>();
            this.TicketReceive1 = new HashSet<TicketReceive>();
            this.TicketReceive2 = new HashSet<TicketReceive>();
            this.Ticket = new HashSet<Ticket>();
            this.Ticket1 = new HashSet<Ticket>();
            this.Ticket2 = new HashSet<Ticket>();
            this.Transfer = new HashSet<Transfer>();
            this.Transfer1 = new HashSet<Transfer>();
            this.TicketPay = new HashSet<TicketPay>();
            this.TicketPay1 = new HashSet<TicketPay>();
            this.TicketPay2 = new HashSet<TicketPay>();
            this.MemberAsset = new HashSet<MemberAsset>();
            this.MemberAsset1 = new HashSet<MemberAsset>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string UserType { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastLogin { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserDetail { get; set; }
        public string UserPageRole { get; set; }
        public string UserPageIndex { get; set; }
        public string UserTypeRole { get; set; }
    
        public virtual ICollection<CompanyAsset> CompanyAsset { get; set; }
        public virtual ICollection<CompanyAsset> CompanyAsset1 { get; set; }
        public virtual ICollection<Member> Member { get; set; }
        public virtual ICollection<Member> Member1 { get; set; }
        public virtual ICollection<TicketReceive> TicketReceive { get; set; }
        public virtual ICollection<TicketReceive> TicketReceive1 { get; set; }
        public virtual ICollection<TicketReceive> TicketReceive2 { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; }
        public virtual ICollection<Ticket> Ticket1 { get; set; }
        public virtual ICollection<Ticket> Ticket2 { get; set; }
        public virtual ICollection<Transfer> Transfer { get; set; }
        public virtual ICollection<Transfer> Transfer1 { get; set; }
        public virtual ICollection<TicketPay> TicketPay { get; set; }
        public virtual ICollection<TicketPay> TicketPay1 { get; set; }
        public virtual ICollection<TicketPay> TicketPay2 { get; set; }
        public virtual ICollection<MemberAsset> MemberAsset { get; set; }
        public virtual ICollection<MemberAsset> MemberAsset1 { get; set; }
    }
}
