//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSH.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collaterals
    {
        public int Id { get; set; }
        public Nullable<decimal> CashPerKg { get; set; }
        public Nullable<decimal> GoldPerKg { get; set; }
        public Nullable<double> GoldPercent { get; set; }
    }
}
