//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSH.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyBank
    {
        public CompanyBank()
        {
            this.MemberAsset = new HashSet<MemberAsset>();
        }
    
        public int BankId { get; set; }
        public string BankRef { get; set; }
        public string BankName { get; set; }
        public string BankBranch { get; set; }
        public string AccountNo { get; set; }
        public string AccountType { get; set; }
        public string AccountName { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<MemberAsset> MemberAsset { get; set; }
    }
}
