//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSH.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugAllergies
    {
        public int DrugAllergyId { get; set; }
        public string UserName { get; set; }
        public string DrugName { get; set; }
        public string Treatment { get; set; }
        public string DrugInformation { get; set; }
    }
}
