//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSH.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalHistories
    {
        public int DiseaseId { get; set; }
        public string UserName { get; set; }
        public string DiseaseName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string DiseaseDetails { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
