//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSH.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalHistoryDetails
    {
        public int DiseaseDtlId { get; set; }
        public Nullable<int> DiseaseId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string DoctorName { get; set; }
        public string HospitalName { get; set; }
        public Nullable<double> Pressure { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Temperature { get; set; }
        public string TreatmentDetails { get; set; }
    }
}
