//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSH.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Ticket = new HashSet<Ticket>();
            this.Trade = new HashSet<Trade>();
            this.Transfer = new HashSet<Transfer>();
            this.MemberAsset = new HashSet<MemberAsset>();
        }
    
        public System.Guid MemberId { get; set; }
        public string MemberRef { get; set; }
        public string MemberClass { get; set; }
        public string MemberType { get; set; }
        public string MemberName { get; set; }
        public Nullable<int> MemberGroup { get; set; }
        public Nullable<int> MemberLevel { get; set; }
        public string MemberTitle { get; set; }
        public string MarketingName { get; set; }
        public Nullable<bool> PauseBuy { get; set; }
        public Nullable<bool> PauseSell { get; set; }
        public Nullable<bool> TradeUnlimit { get; set; }
        public Nullable<int> TradeMaximum { get; set; }
        public Nullable<int> TradeRangePlaced { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string PassportId { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public Nullable<System.DateTime> DateOfExpire { get; set; }
        public string Political { get; set; }
        public string HomeNo { get; set; }
        public string HomeSoi { get; set; }
        public string HomeStreet { get; set; }
        public string HomeSubDistrict { get; set; }
        public string HomeDistrict { get; set; }
        public string HomeProvince { get; set; }
        public string HomePostcode { get; set; }
        public string HomeAddress { get; set; }
        public string PresentAddress { get; set; }
        public string Mobile { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string PassportNo { get; set; }
        public string GovernmentCard { get; set; }
        public string Sex { get; set; }
        public string Nation { get; set; }
        public string Ethnicity { get; set; }
        public string Religion { get; set; }
        public string Education { get; set; }
        public string IncomeMonth { get; set; }
        public string BankName { get; set; }
        public string BankAccountName { get; set; }
        public string BankAccountNo { get; set; }
        public string BankAccountType { get; set; }
        public string BankBranch { get; set; }
        public string BankPayType { get; set; }
        public string WorkType { get; set; }
        public string WorkPlace { get; set; }
        public string WorkBusinessType { get; set; }
        public string WorkTelephone { get; set; }
        public string WorkFax { get; set; }
        public string Status { get; set; }
        public string MateName { get; set; }
        public string MateCareer { get; set; }
        public string MatePolitical { get; set; }
        public string MateTelephone { get; set; }
        public string MateWorkplace { get; set; }
        public string MateBusinessType { get; set; }
        public string EmergencyPersonName { get; set; }
        public string EmergencyRelationship { get; set; }
        public string EmergencyAddress { get; set; }
        public string EmergencyTelephone { get; set; }
        public string CorporateType { get; set; }
        public string CorporateName { get; set; }
        public string CorporateBusinessType { get; set; }
        public string CorporateTradeRegNo { get; set; }
        public string CorporateTaxNo { get; set; }
        public string CorporateHomeNo { get; set; }
        public string CorporateHomeSoi { get; set; }
        public string CorporateHomeStreet { get; set; }
        public string CorporateHomeSubDistrict { get; set; }
        public string CorporateHomeDistrict { get; set; }
        public string CorporateHomeProvince { get; set; }
        public string CorporateHomePostcode { get; set; }
        public string CorporateTelephone { get; set; }
        public string CorporateFax { get; set; }
        public string CorporatePresidentSigned { get; set; }
        public string CorporateContactName { get; set; }
        public string CorporateContactPassportId { get; set; }
        public string CorporateContactTelephone { get; set; }
        public string CorporateContactEmail { get; set; }
        public string CorporateShareHolder1 { get; set; }
        public string CorporateShareHolderRate1 { get; set; }
        public string CorporateShareHolder2 { get; set; }
        public string CorporateShareHolderRate2 { get; set; }
        public string CorporateShareHolder3 { get; set; }
        public string CorporateShareHolderRate3 { get; set; }
        public string CorporateShareHolder4 { get; set; }
        public string CorporateShareHolderRate4 { get; set; }
        public string CorporateShareHolder5 { get; set; }
        public string CorporateShareHolderRate5 { get; set; }
        public string CorporateHasAuthorizer { get; set; }
        public string CorporateNation { get; set; }
        public string CorporateIncome { get; set; }
        public string AuthorizerName { get; set; }
        public string AuthorizerId { get; set; }
        public string AuthorizerAddress { get; set; }
        public string AuthorizerTel { get; set; }
        public string AuthorizerEmail { get; set; }
        public string AttorneyName { get; set; }
        public string AttorneyId { get; set; }
        public string AttorneyAddress { get; set; }
        public string AttorneyTel { get; set; }
        public string AttorneyEmail { get; set; }
        public string PayType { get; set; }
        public string PayBank { get; set; }
        public string PayBankBanch { get; set; }
        public string PayAccountType { get; set; }
        public string PayAccountNo { get; set; }
        public string PayAccountName { get; set; }
        public Nullable<System.DateTime> PayBankApprove { get; set; }
        public string PayApproveId { get; set; }
        public string PayApproveBy { get; set; }
        public Nullable<System.DateTime> PayApporveDate { get; set; }
        public string ApproveRegisterId { get; set; }
        public Nullable<System.DateTime> ApproveRegisterDate { get; set; }
        public string ApproveCollateralId { get; set; }
        public Nullable<System.DateTime> ApproveCollateralDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
    
        public virtual ICollection<Ticket> Ticket { get; set; }
        public virtual ICollection<Trade> Trade { get; set; }
        public virtual ICollection<Transfer> Transfer { get; set; }
        public virtual AspNetUsers UserApproveRegister { get; set; }
        public virtual AspNetUsers UserCreated { get; set; }
        public virtual ICollection<MemberAsset> MemberAsset { get; set; }
    }
}
