//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSH.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberAsset
    {
        public System.Guid AssetId { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public string AssetType { get; set; }
        public Nullable<decimal> AssetCash { get; set; }
        public Nullable<decimal> AssetGold { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public string Direction { get; set; }
        public string PayType { get; set; }
        public string PayTypeDetail { get; set; }
        public Nullable<bool> Active { get; set; }
        public string GoldBrand { get; set; }
        public string GoldSerialNo { get; set; }
        public string Branch { get; set; }
        public string ApproveId { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual Member Member { get; set; }
    }
}
