//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSH.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberAsset
    {
        public System.Guid AssetId { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public string AssetType { get; set; }
        public Nullable<decimal> AssetCash { get; set; }
        public Nullable<decimal> AssetGold { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public string Direction { get; set; }
        public string PayType { get; set; }
        public string PayTypeDetail { get; set; }
        public Nullable<bool> Active { get; set; }
        public string GoldBrand { get; set; }
        public string GoldSerialNo { get; set; }
        public string Branch { get; set; }
        public string ApproveId { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string Status { get; set; }
        public string WithdrawStatus { get; set; }
        public Nullable<System.Guid> WithdrawId { get; set; }
        public string PayChequeNo { get; set; }
        public string PayBankName { get; set; }
        public string PayAccountNo { get; set; }
        public string PayAccountName { get; set; }
        public string PayAccountType { get; set; }
        public string PayBankBranch { get; set; }
        public string PayTime { get; set; }
        public Nullable<System.DateTime> PayDuedate { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<int> CompanyBankId { get; set; }
        public string PayTransRef { get; set; }
    
        public virtual AspNetUsers UserApproved { get; set; }
        public virtual AspNetUsers UserCreated { get; set; }
        public virtual CompanyBank CompanyBank { get; set; }
        public virtual Member Member { get; set; }
    }
}
