//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSH.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay
    {
        public System.Guid PayId { get; set; }
        public string PayRef { get; set; }
        public string TransferType { get; set; }
        public string PayType { get; set; }
        public string PayBank { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Balance { get; set; }
        public string Status { get; set; }
        public string Note { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public string MemberBy { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ApproveBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
