//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSH.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Risk
    {
        public System.Guid RiskId { get; set; }
        public string RiskRef { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public Nullable<bool> Approve { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
    }
}
