//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSH.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpotPrice
    {
        public int SpotId { get; set; }
        public Nullable<decimal> Bid { get; set; }
        public Nullable<decimal> Ask { get; set; }
        public Nullable<decimal> BidThb { get; set; }
        public Nullable<decimal> AskThb { get; set; }
        public string SpotDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> SpotLine { get; set; }
    }
}
