//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSH.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOnline
    {
        public int StockId { get; set; }
        public Nullable<bool> SystemHalt { get; set; }
        public Nullable<decimal> Premium { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<double> MaxKg { get; set; }
        public Nullable<double> MaxKg1 { get; set; }
        public Nullable<double> MaxKg2 { get; set; }
        public Nullable<double> MaxKg3 { get; set; }
        public Nullable<double> MaxKg4 { get; set; }
        public Nullable<double> Spread { get; set; }
        public Nullable<double> Spread1 { get; set; }
        public Nullable<double> Spread2 { get; set; }
        public Nullable<double> Spread3 { get; set; }
        public Nullable<double> Spread4 { get; set; }
        public Nullable<double> Duedate1 { get; set; }
        public Nullable<double> Duedate2 { get; set; }
        public Nullable<double> Duedate3 { get; set; }
        public Nullable<double> Duedate4 { get; set; }
        public Nullable<double> CreditLimit1 { get; set; }
        public Nullable<double> CreditLimit2 { get; set; }
        public Nullable<double> CreditLimit3 { get; set; }
        public Nullable<double> CreditLimit4 { get; set; }
        public Nullable<double> MarginType1 { get; set; }
        public Nullable<double> MarginType2 { get; set; }
        public Nullable<double> MarginType3 { get; set; }
        public Nullable<double> MarginType4 { get; set; }
        public Nullable<double> TradeQuantityLimit { get; set; }
        public Nullable<double> RangePlaceOrder { get; set; }
        public Nullable<decimal> AskThbSelf { get; set; }
        public string SpotCalculate { get; set; }
    }
}
