//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSH.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.TicketReceive = new HashSet<TicketReceive>();
        }
    
        public System.Guid TicketId { get; set; }
        public string TicketRef { get; set; }
        public string TicketType { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public string TradeRef { get; set; }
        public string Status { get; set; }
        public string Purity { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<bool> Active { get; set; }
        public string PayStatus { get; set; }
        public Nullable<bool> UseDeposit { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string PayType { get; set; }
        public string PayId { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public string ApprovePayId { get; set; }
        public Nullable<System.DateTime> ApprovePayDate { get; set; }
        public string ApproveId { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual AspNetUsers AspNetUsers2 { get; set; }
        public virtual Member Member { get; set; }
        public virtual ICollection<TicketReceive> TicketReceive { get; set; }
    }
}
