//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSH.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketReceive
    {
        public System.Guid ReceiveId { get; set; }
        public string ReceiveRef { get; set; }
        public Nullable<System.Guid> TicketId { get; set; }
        public string ReceiveType { get; set; }
        public string Type { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Status { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ApprovePayId { get; set; }
        public Nullable<System.DateTime> ApprovePayDate { get; set; }
        public string ApproveId { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual AspNetUsers AspNetUsers2 { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
