//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSH.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketReceive
    {
        public System.Guid ReceiveId { get; set; }
        public string ReceiveRef { get; set; }
        public Nullable<System.Guid> TicketId { get; set; }
        public string ReceiveType { get; set; }
        public string Type { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Status { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ApprovePayId { get; set; }
        public Nullable<System.DateTime> ApprovePayDate { get; set; }
        public string ApproveId { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string PayChequeNo { get; set; }
        public string PayBankName { get; set; }
        public string PayAccountNo { get; set; }
        public string PayAccountName { get; set; }
        public string PayAccountType { get; set; }
        public string PayBankBranch { get; set; }
        public string PayTransRef { get; set; }
        public string PayTime { get; set; }
        public Nullable<System.DateTime> PayDuedate { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<int> CompanyBankId { get; set; }
    
        public virtual Ticket Ticket { get; set; }
        public virtual AspNetUsers UserApprove { get; set; }
        public virtual AspNetUsers UserApprovePay { get; set; }
        public virtual AspNetUsers UserCreated { get; set; }
    }
}
