//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSH.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade
    {
        public System.Guid TradeId { get; set; }
        public string TradeRef { get; set; }
        public string TradeType { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<bool> Leave { get; set; }
        public string Purity { get; set; }
        public string IpAddress { get; set; }
        public string AcceptType { get; set; }
        public string RejectType { get; set; }
        public string Status { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public Nullable<System.Guid> SaleId { get; set; }
        public Nullable<bool> UseDeposit { get; set; }
        public Nullable<bool> TradeLot { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual UserOnline UserOnline { get; set; }
    }
}
