//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSH.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeLot
    {
        public int TradeLotId { get; set; }
        public string TradeLotRef { get; set; }
        public string TradeType { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public string Status { get; set; }
    
        public virtual UserOnline UserOnline { get; set; }
    }
}
