//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSH.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOnline
    {
        public UserOnline()
        {
            this.Trade = new HashSet<Trade>();
            this.TradeLot = new HashSet<TradeLot>();
        }
    
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public string Role { get; set; }
        public Nullable<int> UserLevel { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Helt { get; set; }
        public Nullable<bool> FirstTime { get; set; }
        public Nullable<bool> Online { get; set; }
        public Nullable<System.DateTime> OnlineTime { get; set; }
        public string OnlineId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> UpdateBy { get; set; }
    
        public virtual ICollection<Trade> Trade { get; set; }
        public virtual ICollection<TradeLot> TradeLot { get; set; }
    }
}
