//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSH.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewOfCreditLine
    {
        public Nullable<long> Id { get; set; }
        public double DepositGold { get; set; }
        public decimal AssetCash { get; set; }
        public decimal AssetGold { get; set; }
        public string FirstName { get; set; }
        public string MemberRef { get; set; }
        public System.Guid MemberId { get; set; }
        public Nullable<decimal> CashPerKg { get; set; }
        public Nullable<decimal> GoldPerKg { get; set; }
        public Nullable<double> GoldPercent { get; set; }
        public double BuyQuantity { get; set; }
        public double SellQuantity { get; set; }
        public double BuyQuantityLeave { get; set; }
        public double SellQuantityLeave { get; set; }
        public double SellQuantityGoldDep { get; set; }
    }
}
